version: 1.0.{build}
before_build:
- cmd: nuget restore
build:
  publish_nuget: true
  publish_nuget_symbols: true
  include_nuget_references: true
  verbosity: minimal
artifacts:
- path: OfficeCommunicatorInstallScript.iss
deploy:
- provider: GitHub
  tag: OfficeCommunicator-v$(appveyor_build_version)
  release: OfficeCommunicator-v$(appveyor_build_version)
  auth_token:
    secure: wG4pjO2AsPPA2ELvrOCaRHw2tVHvp4uRQsew7traQZpqTQLTqXZNHnFoZDkgk4I5
  artifact: OfficeCommunicatorInstallScript.iss
  prerelease: false
  draft: true